const TYPES = {
    REQUEST_HEROES: 'REQUEST_HEROES',
    FETCH_HEROES_SUCCESS: 'FETCH_HEROES_SUCCESS',
    REQUEST_ERROR: 'REQUEST_ERROR',
    SET_FETCHING_STATUS: 'SET_FETCHING_STATUS',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    REQUEST_HERO: 'REQUEST_HERO',
    GET_HERO_SUCCESS: 'GET_HERO_SUCCESS',
}

export default TYPES