const TYPES = {
    REQUEST_HEROES: 'REQUEST_HEROES',
    FETCH_HEROES_SUCCESS: 'FETCH_HEROES_SUCCESS',
    REQUEST_ERROR: 'REQUEST_ERROR',
    SET_FETCHING_STATUS: 'SET_FETCHING_STATUS',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    REQUEST_HERO: 'REQUEST_HERO',
    GET_HERO_SUCCESS: 'GET_HERO_SUCCESS',
    REQUEST_UPDATE_HERO_DATA: 'REQUEST_UPDATE_HERO_DATA',
    UPDATE_HERO_SUCCESS: 'UPDATE_HERO_SUCCESS',
    REQUEST_DELETE_HERO: 'REQUEST_DELETE_HERO',
    DELETE_HERO_SUCCESS: 'DELETE_HERO_SUCCESS',
    DELETE_IMAGES_SUCCESS: 'DELETE_IMAGES_SUCCESS',
    REQUEST_DELETE_IMAGES: 'REQUEST_DELETE_IMAGES',
    REQUEST_ADD_IMAGE: 'REQUEST_ADD_IMAGE',
    ADD_IMAGE_SUCCESS: 'ADD_IMAGE_SUCCESS',
    REQUEST_CREATE_HERO: 'REQUEST_CREATE_HERO',
    CREATE_HERO_SUCCESS: 'CREATE_HERO_SUCCESS',
}

export default TYPES